import { defineConfig } from 'orval'

// Generates the typed API client from openapi.json (written by `npm run export:openapi` in backend/).
// Never edit src/api/generated by hand — rerun `npm run generate-client`.
export default defineConfig({
  api: {
    input: './openapi.json',
    output: {
      mode: 'tags-split',
      target: './src/api/generated/endpoints',
      schemas: './src/api/generated/model',
      client: 'axios-functions',
      clean: true,
      override: {
        mutator: { path: './src/api/http.ts', name: 'apiClient' },
      },
    },
  },
})
